// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl109YkkW9I7exc2tTx5Xg4m4zzCsxp0k',
    appId: '1:211555647968:web:0ebbbef5d6fc2ebdbdab85',
    messagingSenderId: '211555647968',
    projectId: 'mynotes-project-e3a24',
    authDomain: 'mynotes-project-e3a24.firebaseapp.com',
    storageBucket: 'mynotes-project-e3a24.firebasestorage.app',
    measurementId: 'G-N9ZKHNZSQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8Fqu_bYfgjxAvo_w1JtnQ5Pbmjn6L7Co',
    appId: '1:211555647968:android:0ad94cbf734d3496bdab85',
    messagingSenderId: '211555647968',
    projectId: 'mynotes-project-e3a24',
    storageBucket: 'mynotes-project-e3a24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUr17HL87bIT3WKab2yUgku4i79txvfMM',
    appId: '1:211555647968:ios:a3311f3fff12fdc0bdab85',
    messagingSenderId: '211555647968',
    projectId: 'mynotes-project-e3a24',
    storageBucket: 'mynotes-project-e3a24.firebasestorage.app',
    iosBundleId: 'note.com.mynote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUr17HL87bIT3WKab2yUgku4i79txvfMM',
    appId: '1:211555647968:ios:a3311f3fff12fdc0bdab85',
    messagingSenderId: '211555647968',
    projectId: 'mynotes-project-e3a24',
    storageBucket: 'mynotes-project-e3a24.firebasestorage.app',
    iosBundleId: 'note.com.mynote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl109YkkW9I7exc2tTx5Xg4m4zzCsxp0k',
    appId: '1:211555647968:web:dfe8b6e9fe16f233bdab85',
    messagingSenderId: '211555647968',
    projectId: 'mynotes-project-e3a24',
    authDomain: 'mynotes-project-e3a24.firebaseapp.com',
    storageBucket: 'mynotes-project-e3a24.firebasestorage.app',
    measurementId: 'G-6608WZNWCZ',
  );
}
